# データの確認

## 準備コード

In [ ]:
import duckdb
import pandas as pd
import numpy as np

In [15]:
def get_data_with_duckdb(db_path, query):
    """
    duckdbデータベースからデータを取得する関数
    :param db_path: メインのSQLiteデータベースのパス
    :param query: 実行するSQLクエリ
    :return: pandas DataFrame
    """
    # データベースに接続
    con = duckdb.connect(db_path)

    # 結果を取得
    df = con.execute(query).fetchdf()
    # 接続を閉じる
    con.close()
    return df

In [28]:
# インメモリのduckdbデータベースを使用してデータを取得する関数
def get_data_with_duckdb_in_memory(df,query, table_name='my_table'):
    """
    インメモリのduckdbデータベースを使用してデータを取得する関数
    :param df: pandas DataFrame
    :param table_name: 一時テーブルの名前
    :param query: 実行するSQLクエリ
    :return: pandas DataFrame
    """
    # インメモリデータベースに接続
    con = duckdb.connect(':memory:')
    
    # データフレームを登録（一時テーブルとして）
    con.register(table_name, df)
    
    # SQLクエリを実行
    result_df = con.execute(query).fetchdf()
    
    # 接続を閉じる
    con.close()
    
    return result_df

## 実行

In [12]:
# データベースに接続
db_path = r"D:\kengo\data\browser_log.db"

In [18]:
# SQL文を実行
query = f"""
SELECT 
    sample_id,
    COUNT(*) as count
FROM browserlog_201902
GROUP BY sample_id
"""

df = get_data_with_duckdb(db_path, query)

In [20]:
# SQL文を実行
query = f"""
SELECT 
    DATE(access_time) as date,
    COUNT(*) as count
FROM browserlog_201902
GROUP BY DATE(access_time)
ORDER BY DATE(access_time)
"""

df = get_data_with_duckdb(db_path, query)

In [22]:
# SQL文を実行
query = f"""
SELECT 
    *
FROM browserlog_201902
WHERE DATE(access_time) BETWEEN '2019-02-01' AND '2019-02-10'
"""

df = get_data_with_duckdb(db_path, query)

In [39]:
# SQL文を実行
query = f"""
SELECT 
    *
FROM browserlog_201902
WHERE DATE(access_time) > DATE '2019-02-10' and sample_id = 'Ljgje3D4'
ORDER BY access_time
"""

df_Ljgje3D4 = get_data_with_duckdb(db_path, query)

In [40]:
# 結果を表示
display(df_Ljgje3D4)

,sample_id,access_time,site_name,site_id,url
0,Ljgje3D4,2019-02-11 00:05:16,blogspot.com,56.0,http://racchie-alchemist.blogspot.com/2015/08/...
1,Ljgje3D4,2019-02-11 00:13:41,www.a-q-f.com,152.0,https://www.a-q-f.com/openpc/TBServiceLink.do
2,Ljgje3D4,2019-02-11 00:13:43,www.a-q-f.com,152.0,https://www.a-q-f.com/openpc/TBServiceLink.do
3,Ljgje3D4,2019-02-11 00:13:43,www.a-q-f.com,152.0,https://www.a-q-f.com/saison/gaingame/index.html
4,Ljgje3D4,2019-02-11 00:13:45,www.a-q-f.com,152.0,https://www.a-q-f.com/contents/extra/gaingame/...
...,...,...,...,...,...
185822,Ljgje3D4,2019-02-28 23:50:57,g-game.a-q-f.com,3873.0,http://g-game.a-q-f.com/jewel/battle/198920430...
185823,Ljgje3D4,2019-02-28 23:51:01,g-game.a-q-f.com,3873.0,http://g-game.a-q-f.com/jewel/battle_result/19...
185824,Ljgje3D4,2019-02-28 23:51:04,g-game.a-q-f.com,3873.0,http://g-game.a-q-f.com/jewel/game_over/469257033
185825,Ljgje3D4,2019-02-28 23:51:07,g-game.a-q-f.com,3873.0,http://g-game.a-q-f.com/jewel/goal_result/4692...
185826,Ljgje3D4,2019-02-28 23:51:11,g-game.a-q-f.com,3873.0,http://g-game.a-q-f.com/jewel

In [45]:
# インメモリのduckdbデータベースを使用してデータを取得
table_name = 'my_table'
query = f'''
SELECT
    DATE(access_time) as date,
    count(*) as count 
FROM {table_name}
GROUP BY DATE(access_time)
ORDER BY DATE(access_time)
'''

# query = f'''
# SELECT 
#     sample_id
# FROM {table_name}
# GROUP BY sample_id
# '''

df_Ljgje3D4_result = get_data_with_duckdb_in_memory(df_Ljgje3D4, query, table_name)
display(df_Ljgje3D4_result)

         date  count
0  2019-02-11  10966
1  2019-02-12   9790
2  2019-02-13   9109
3  2019-02-14  10483
4  2019-02-15  11184
5  2019-02-16  10632
6  2019-02-17  11865
7  2019-02-18   7592
8  2019-02-19  11069
9  2019-02-20  10512
10 2019-02-21   8124
11 2019-02-22   9277
12 2019-02-23   9841
13 2019-02-24  14356
14 2019-02-25  10629
15 2019-02-26  12641
16 2019-02-27   6385
17 2019-02-28  11372

In [ ]:
# 結果を表示
display(df)

         date    count
0  2019-02-01  5217931
1  2019-02-02  5286097
2  2019-02-03  5334806
3  2019-02-04  5298699
4  2019-02-05  5131388
5  2019-02-06  5170397
6  2019-02-07  5021613
7  2019-02-08  4914365
8  2019-02-09  5390673
9  2019-02-10  5132679
10 2019-02-11  5514664
11 2019-02-12  5010227
12 2019-02-13  4974322
13 2019-02-14  4901683
14 2019-02-15  4927007
15 2019-02-16  5085908
16 2019-02-17  5268575
17 2019-02-18  5066214
18 2019-02-19  5145890
19 2019-02-20  5055947
20 2019-02-21  4962549
21 2019-02-22  4859064
22 2019-02-23  5250939
23 2019-02-24  5213888
24 2019-02-25  5081056
25 2019-02-26  4955124
26 2019-02-27  5077734
27 2019-02-28  5172953

In [23]:
display(df)

,sample_id,access_time,site_name,site_id,url
0,4RraWrV4,2019-02-05 21:57:23,www.amazon.co.jp,153.0,https://www.amazon.co.jp/
1,4RraWrV4,2019-02-05 21:57:24,www.amazon.co.jp,153.0,https://www.amazon.co.jp/
2,4RraWrV4,2019-02-05 21:57:26,www.amazon.co.jp,153.0,https://www.amazon.co.jp/
3,4RraWrV4,2019-02-05 21:57:47,www.amazon.co.jp,153.0,https://www.amazon.co.jp/gp/your-account/order...
4,4RraWrV4,2019-02-05 21:58:03,www.yahoo.co.jp,114.0,https://www.yahoo.co.jp/
...,...,...,...,...,...
51898643,9DzBz1k4,2019-02-10 07:14:31,mail.ocn.ne.jp,970.0,https://mail.ocn.ne.jp/ocn/mail
51898644,9DzBz1k4,2019-02-10 07:11:03,facebook.com,30.0,https://www.facebook.com/messages/t/kaoru.kawa...
51898645,9DzBz1k4,2019-02-10 07:10:33,facebook.com,30.0,https://www.facebook.com/messages/t/kaoru.kawa...
51898646,9DzBz1k4,2019-02-10 07:09:26,facebook.com,30.0,https://www.facebook.com/messages/t/kaoru.kawa...
51898647,9DzBz1k4,2019-02-10 07:08:26,facebook.com,30.0,https://www.facebook.com/messages/t/kaoru.kawa...

In [35]:
# インメモリのduckdbデータベースを使用してデータを取得
table_name = 'my_table'
query = f'''
SELECT
    sample_id,
    count(*) as count 
FROM {table_name}
GROUP BY sample_id
ORDER BY count DESC
'''
df_result = get_data_with_duckdb_in_memory(df, query, table_name)

In [36]:
display(df_result)

      sample_id   count
0      4rDoOQB9  485330
1      Ljgje3D4  103508
2      L77abAkL   96182
3      Llb0VrGw   95349
4      9BK3WyYL   62655
...         ...     ...
46173  9WvZ7kWw       1
46174  4rD0pjv9       1
46175  9XOY8bQw       1
46176  4K5EgEv9       1
46177  w3dMeYM9       1

[46178 rows x 2 columns]

In [41]:
len(df)

51898648

## 使えない（sqlite）

In [ ]:
import sqlite3
def get_data_with_sqlite(db_path, query):
    """
    SQLiteデータベースからデータを取得する関数
    :param db_path: メインのSQLiteデータベースのパス
    :param query: 実行するSQLクエリ
    :return: pandas DataFrame
    """
    # データベースに接続
    con = sqlite3.connect(db_path)

    # 結果を取得
    df = pd.read_sql_query(query, con)
    # 接続を閉じる
    con.close()
    return df